### PR TITLE
Munin plugin

### PR DESCRIPTION
**Pull request by sumpfralle**
Munin plugin for tracking the distribution (and amount) of the supported transport security levels (plain/tor/tls).

The changeset is based on #14.

### CODE REVIEW

**Comment by t2d** [comment]
Can you please check why your tests don't pass?

**Comment by sumpfralle** [comment]
Fixed - thanks for the hint!

**Comment by sumpfralle** [comment]
Just for visualization: here is a graph produced by the munin plugin code above:

mail_tls_helper-day

**Comment by t2d** [comment]
Thanks a lot for this great PR. Sorry for the delay, but I just wanted to check in detail.

**Comment by sumpfralle** [comment]
Thank you for merging!

**Pull request merged**
